In [4]:
import gc
import math
import calendar
from datetime import datetime
import pandas as pd

In [ ]:
data1 = pd.read_csv('./dataset/big_data_set1_f.csv', encoding='cp949')
data2 = pd.read_csv('./dataset/big_data_set2_f.csv', encoding='cp949')
data3 = pd.read_csv('./dataset/big_data_set3_f.csv', encoding='cp949')

data = pd.merge(data2, data3, on=['ENCODED_MCT' ,'TA_YM'], how='inner')
data = pd.merge(data, data1, on='ENCODED_MCT', how='left')

del data1, data2, data3
gc.collect()

data

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,MCT_BSE_AR,MCT_NM,MCT_BRD_NUM,MCT_SIGUNGU_NM,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4_50-75%,5_75-90%,5_75-90%,5_75-90%,5_75-90%,1_상위1구간,-999999.9,2.6,...,12.5,75.0,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4_50-75%,6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),NaN,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2_10-25%,4_50-75%,4_50-75%,4_50-75%,2_10-25%,1_상위1구간,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5_75-90%,2_10-25%,1_10%이하,1_10%이하,6_90%초과(하위 10% 이하),2_상위2구간,2.6,249.7,...,4.3,24.4,서울특별시 성동구 행당로5길 2,메가***********,커피전문점2,서울 성동구,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2_10-25%,2_10-25%,2_10-25%,2_10-25%,3_25-50%,1_상위1구간,19.2,196.7,...,7.4,55.9,서울 성동구 한림말1길 8.,콩물*****,NaN,서울 성동구,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6_90%초과(하위 10% 이하),2_10-25%,4_50-75%,4_50-75%,1_10%이하,6_상위6구간(하위1구간),1.6,176.3,...,41.7,41.7,서울특별시 성동구 상원4길 11,우아**,NaN,서울 성동구,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1_10%이하,2_10-25%,2_10-25%,2_10-25%,4_50-75%,2_상위2구간,24.0,116.5,...,11.3,48.7,서울 성동구 왕십리로 223-1,밸런***,샌드위치/토스트1,서울 성동구,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2_10-25%,2_10-25%,3_25-50%,3_25-50%,3_25-50%,1_상위1구간,12.8,215.6,...,25.0,50.0,서울 성동구 용답중앙15길 13.,미*,NaN,서울 성동구,중식당,답십리,20131128,NaN

In [ ]:
data_prep = data.drop(columns=['MCT_BRD_NUM', 'MCT_SIGUNGU_NM', 'MCT_NM', 'MCT_BSE_AR', 'MCT_BSE_AR'])
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4_50-75%,5_75-90%,5_75-90%,5_75-90%,5_75-90%,1_상위1구간,-999999.9,2.6,...,6.0273,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4_50-75%,6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,96.6,...,2.2352,10.66,6.12,23.8,23.8,52.4,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,108.0,...,3.3415,10.41,6.30,11.5,11.5,76.9,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2_10-25%,4_50-75%,4_50-75%,4_50-75%,2_10-25%,1_상위1구간,-999999.9,74.2,...,2.0480,9.86,4.69,13.0,17.4,69.6,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5_75-90%,2_10-25%,1_10%이하,1_10%이하,6_90%초과(하위 10% 이하),2_상위2구간,2.6,249.7,...,4.3371,43.31,10.15,71.3,4.3,24.4,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2_10-25%,2_10-25%,2_10-25%,2_10-25%,3_25-50%,1_상위1구간,19.2,196.7,...,8.5137,19.29,8.75,36.8,7.4,55.9,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6_90%초과(하위 10% 이하),2_10-25%,4_50-75%,4_50-75%,1_10%이하,6_상위6구간(하위1구간),1.6,176.3,...,5.4627,18.24,12.94,16.7,41.7,41.7,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1_10%이하,2_10-25%,2_10-25%,2_10-25%,4_50-75%,2_상위2구간,24.0,116.5,...,1.8656,28.92,7.88,40.0,11.3,48.7,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2_10-25%,2_10-25%,3_25-50%,3_25-50%,3_25-50%,1_상위1구간,12.8,215.6,...,2.6640,31.16,4.15,25.0,25.0,50.0,중식당,답십리,20131128,NaN

In [ ]:
columns_to_split = ['MCT_OPE_MS_CN', 'RC_M1_SAA', 'RC_M1_TO_UE_CT','RC_M1_UE_CUS_CN','RC_M1_AV_NP_AT','APV_CE_RAT']

for c in columns_to_split:
    mask = data_prep[c].notna()
    data_prep.loc[mask, c] = data_prep.loc[mask, c].astype(str).str.split('_').str[0].astype(int)
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4,5,5,5,5,1,-999999.9,2.6,...,6.0273,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2,3,4,4,2,6,-999999.9,96.6,...,2.2352,10.66,6.12,23.8,23.8,52.4,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2,3,4,4,2,6,-999999.9,108.0,...,3.3415,10.41,6.30,11.5,11.5,76.9,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2,4,4,4,2,1,-999999.9,74.2,...,2.0480,9.86,4.69,13.0,17.4,69.6,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5,2,1,1,6,2,2.6,249.7,...,4.3371,43.31,10.15,71.3,4.3,24.4,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2,2,2,2,3,1,19.2,196.7,...,8.5137,19.29,8.75,36.8,7.4,55.9,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6,2,4,4,1,6,1.6,176.3,...,5.4627,18.24,12.94,16.7,41.7,41.7,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1,2,2,2,4,2,24.0,116.5,...,1.8656,28.92,7.88,40.0,11.3,48.7,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2,2,3,3,3,1,12.8,215.6,...,2.6640,31.16,4.15,25.0,25.0,50.0,중식당,답십리,20131128,NaN

In [ ]:
data_prep['HPSN_MCT_BZN_CD_NM'].fillna('비상권', inplace=True)

/tmp/ipython-input-1637789189.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_prep['HPSN_MCT_BZN_CD_NM'].fillna('비상권', inplace=True)

In [ ]:
data_prep['ARE_D'] = pd.to_numeric(data_prep['ARE_D'], errors='coerce')
data_prep['MCT_ME_D'] = pd.to_numeric(data_prep['MCT_ME_D'], errors='coerce')

data_prep['ARE_D'] = data_prep['ARE_D'].astype('Int64')
data_prep['MCT_ME_D'] = data_prep['MCT_ME_D'].astype('Int64')

na_rows = data_prep['MCT_ME_D'].isna()
data_prep['survive'] = na_rows
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,<NA>,True
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,<NA>,True
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,<NA>,True
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,<NA>,True
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,<NA>,True

In [ ]:
for idx in data_prep.index:
    tmp = data_prep.loc[idx]
    try:
        if tmp['TA_YM'] == tmp['MCT_ME_D']//100:
            data_prep.loc[idx, 'survive'] = 0
        else:
            data_prep.loc[idx, 'survive'] = 1
    except:
        data_prep.loc[idx, 'survive'] = 1

data_prep

/tmp/ipython-input-2165275645.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_prep.loc[idx, 'survive'] = 1

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,<NA>,1
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,<NA>,1
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,<NA>,1
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,<NA>,1
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,<NA>,1

In [ ]:
def get_last_day_from_yyyymm(yyyymm):
    if pd.isna(yyyymm):
        return None
    y = int(yyyymm // 100)
    m = int(yyyymm % 100)
    d = calendar.monthrange(y, m)[1]
    return y * 10000 + m * 100 + d

replacement_dates = data_prep.loc[na_rows, 'TA_YM'].apply(get_last_day_from_yyyymm)

data_prep['MCT_ME_D'] = data_prep['MCT_ME_D'].fillna(replacement_dates)

date1_series = pd.to_datetime(data_prep['ARE_D'].astype(str), format='%Y%m%d', errors='coerce')
date2_series = pd.to_datetime(data_prep['MCT_ME_D'].astype(str), format='%Y%m%d', errors='coerce')

data_prep['day_diff'] = (date2_series - date1_series).dt.days.abs()

data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive,day_diff
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,20230131,1,340
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,20230228,1,368
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,20230331,1,399
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,20230430,1,429
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,20230531,1,460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,20240831,1,2980
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,20240930,1,3010
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,20241031,1,3041
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,20241130,1,3071
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,20241231,1,3102

In [ ]:
data_prep.drop(columns=['ARE_D','MCT_ME_D'], inplace=True)
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,survive,day_diff
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.0000,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,340
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,368
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,399
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.0000,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,1,429
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.0000,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,1.0695,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,1,2980
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,1.0120,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,1,3010
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,1.0741,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,1,3041
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,1.1450,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,1,3071
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,1.2908,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,1,3102

In [ ]:
def quaters(x):
    mm = int(str(x['TA_YM'])[-2:])
    return ((mm-1) // 3) + 1

data_prep['quaters'] = data_prep.apply(quaters, axis=1)
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,survive,day_diff,quaters
0,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,340,1
1,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,368,1
2,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,399,1
3,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,1,429,2
4,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,460,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,1,2980,3
86586,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,1,3010,3
86587,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,1,3041,4
86588,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,1,3071,4
86589,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,1,3102,4

In [ ]:
data_prep.to_csv('./dataset/BasicData_Prep4.csv', encoding='cp949')